name: Block PRs not from develop to master

on:
  pull_request:
    branches:
      - master

jobs:
  check-pr-source:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if PR is not from develop
        if: github.head_ref != 'develop'
        run: |
          echo "PRs to master must come from develop."
          exit 1
